- name: Create app directory
  hosts: webservers
  become: yes
  tasks:
    - name: Create /var/app directory
      file:
        path: /var/app
        state: directory
        mode: '0755'
        owner: deploy
        group: deploy
